---
default_stages:
  - pre-commit
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Validate Docker Compose
  - repo: local
    hooks:
      - name: Validate Docker Compose Files
        id: docker-compose-validate
        pass_filenames: false
        entry: bash -c 'docker compose -f services/compose.yaml config && docker compose -f monitoring/compose.yaml config'
        language: system
        files: "(services|logs|monitoring)/compose\\.ya?ml$"

  # Validate syntax of frontend Dockerfiles
  - repo: https://github.com/hadolint/hadolint
    rev: v2.11.0
    hooks:
      - name: Lint Dockerfiles
        id: hadolint-docker
        files: "(^|/)([Dd]ockerfile|docker-compose\\.ya?ml)$"

  # Validate YAML files
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - name: Lint YAML files
        id: yamllint
        args:
          [
            "-d {extends: relaxed, rules: {line-length: disable}, ignore: chart}",
            "-s",
          ]
        files: \.(yml|yaml)$
        types: [yaml, file]

  # Gitleaks to prevent secrets from being committed
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.2
    hooks:
      - name: Gitleaks
        id: gitleaks-docker
        args: ["--verbose", "--redact"]
        files: .*
