services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - ${PROMETHEUS_PORT}:${PROMETHEUS_PORT}
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - traefik_network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - ${CADVISOR_PORT}:${CADVISOR_PORT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys:/sys
      - /:/rootfs
    networks:
      - traefik_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - ${GRAFANA_PORT}:${GRAFANA_PORT}
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - traefik_network

volumes:
  grafana_data:

networks:
  traefik_network:
    external: true
