name: Deploy Docker Stack

on: 
  push: 
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Docker Stack
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACTIONS_TOKEN }}
      
      - name: Lint Dockerfiles
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: |
            ./services/backend/Dockerfile
            ./services/frontend/Dockerfile

      - name: Validate Docker Compose files
        run: |
          docker compose -f ./services/compose.yaml config
          docker compose -f ./monitoring/compose.yaml config
        
      - name: Build and push Backend Docker image
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
        run: |
          docker build \
            --build-arg POSTGRES_USER=$POSTGRES_USER \
            --build-arg POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
            --build-arg POSTGRES_DB=$POSTGRES_DB \
            --build-arg BACKEND_PORT=$BACKEND_PORT \
            -t ghcr.io/${{ github.repository }}/backend:latest ./services/backend
          
          docker push ghcr.io/${{ github.repository }}/backend:latest

      - name: Build and push Frontend Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/frontend:latest ./services/frontend
          docker push ghcr.io/${{ github.repository }}/frontend:latest
      
      - name: Validate docker-compose stack
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
        run: |
          # Generar un archivo .env temporal con las variables de entorno
          echo "POSTGRES_USER=$POSTGRES_USER" >> .env
          echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
          echo "POSTGRES_DB=$POSTGRES_DB" >> .env
          echo "BACKEND_PORT=$BACKEND_PORT" >> .env

          docker compose -f ./services/compose.yaml up -d

          # Esperar unos segundos para que los servicios se inicialicen
          sleep 10

          # Verificar que todos los contenedores están saludables
          if [ $(docker ps --filter "status=running" | wc -l) -lt 4 ]; then
            echo "Not all containers are healthy"; 
            docker-compose logs;
            exit 1; 
          fi

      - name: Clean up services
        if: always()
        run: |
          docker-compose down